dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.5.0"
  - "smartcontractkit/chainlink-brownie-contracts@0.4.0"
  - "safe-global/safe-contracts@1.3.0"
  - "Uniswap/v2-periphery@1.0.0-beta.0"

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
      - "@gnosis.pm=safe-global/safe-contracts@1.3.0"
      - "@uniswap=Uniswap/v2-periphery@1.0.0-beta.0"

    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
        verify: False
    live:
        gas_limit: auto
        gas_buffer: 1.2
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false
    tests:
        gas_buffer: 1.5
    goerli:
      verify: True
    matic:
      verify: True
    polygon-test:
      verify: True
    bsc-test:
      verify: True
    mumbai_moralis:
      verify: True
    rinkeby:
      verify: True
    bsc-main:
      verify: True
reports:
    exclude_paths: null
    exclude_contracts: null
    only_include_project: true

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true  



wallets:
    from_key: ${PRIVATE_KEY_2}
